@startuml

left to right direction

actor User


rectangle "Expense Tracker System UseCase" {

  usecase "Login" as UC_Login
  usecase "Register" as UC_Register
  usecase "Add Expense" as UC_Add
  usecase "Update Expense" as UC_Update
  usecase "Delete Expense" as UC_Delete
  usecase "View All Expenses" as UC_ViewAll
  usecase "Search Expense by Title" as UC_SearchTitle
  usecase "Filter by Category" as UC_FilterCategory
  usecase "Filter by Date Range" as UC_FilterDate
  usecase "Get Total Expenses" as UC_Total

}

User --> UC_Login
User --> UC_Register
User --> UC_Add
User --> UC_Update
User --> UC_Delete
User --> UC_ViewAll
User --> UC_SearchTitle
User --> UC_FilterCategory
User --> UC_FilterDate
User --> UC_Total

@enduml
